### PR TITLE
Add resolution to counter

### PR DESCRIPTION
**Pull request by andymac4182**
Adding resolution option to counter to allow for logging of items very specified number of times. Defaulted to every time. This is to replace #8 as per the conversation on the PR.

### CODE REVIEW

**Comment by mivano** [comment]
Looks nice! Changing the default template might be a bit breaking maybe. If we really want to avoid that we should introduce a new ResolutionCountOperation instead. I m however not too worried about the additional resolution in the template (I never envisioned that every count will be written anyway) so we might just take it as is. 

@nblumhardt any ideas from your side?

**Comment by andymac4182** [comment]
I could make it that if they don't specify a resolution it uses the old template and if they specify a resolution then it uses the new template. That way it won't break existing logging. 

Would that help?

**Comment by nblumhardt** [comment]
The dynamic template selection sounds like it could be a winner. Having the resolution in the template would definitely be a good reminder for anyone viewing the event that in actuality many more may have occurred... I'm fine with it either way though. Thanks @andymac4182 for the new PR!

**Comment by andymac4182** [comment]
I have updated the template loading and tests. I changed the property name to CounterResolution so as not to clash with anyone using resolution as a property already.

**Comment by mivano** [comment]
Perfect! thanks for the PR, a new package will be out soon.

**Pull request merged**
