### PR TITLE
Add .NET Standard support

### PR DESCRIPTION
**Pull request by jeremymeng**

### CODE REVIEW

**Comment by jeremymeng** [comment]
Successful AppVeyor build: https://ci.appveyor.com/project/jeremymeng/serilog-metrics

Looks like the official AppVeyor build settings would need to be updated.

**Comment by mivano** [comment]
Great work @jeremymeng ! At first glance it looks super. I will go through it in more detail, hopefully this weekend and see if I can get it published via AppVeyor. Thanks!

**Comment by mivano** [comment]
Thanks @jeremymeng. I made a couple of other changed and pushed to appveyor.

**Comment by jeremymeng** [comment]
Awesome! Thanks.

**Pull request merged**
